### ISSUE TITLE
Visual nitpics

### ISSUE THREAD

**Issue by valekjo** [apify/apify-docs#805] opened 2023-12-28 07:23 UTC
- `line-height: tight` in search looks bad
 - double clicking title selects also prefix pill – makes it harder to copypaste
 
<img width="682" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkNLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cb55b47e51398d75383570a36ac30c9adc30639/image.png" alt="image.png" />
<img width="960" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkdLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--123aff4398e2eb9c4cff6e548040a642f4103537/image.png" alt="image.png" />

Reported on slack: https://apifier.slack.com/archives/C0L33UM7Z/p1703684285889429

**Comment by jbartadev** [comment] 2024-01-03 13:38
@webrdaniel Seems like the issue is that it worked locally but not on prod and tooling team seems to be already dealing with it here https://github.com/apify/apify-docs/pull/807

**Comment by m-murasovs** [comment] 2024-01-10 12:47
cc @webrdaniel 
Reported by Pavel: This also causes some issues for google indexing, so it would be good to keep an eye on this

<img width="373" alt="Screenshot 2024-01-10 at 13 45 20" src="https://github.com/apify/apify-docs/assets/38246758/e27fe0ce-90d9-4b31-b474-2605d022fe60">

**Comment by B4nan** [comment] 2024-01-10 12:49
Hmm, maybe we should try to replace those badges with empty `<span>` that has the text added via CSS?

**Comment by webrdaniel** [comment] 2024-01-12 14:10
line-height fixed by https://github.com/apify/apify-docs/pull/807 
For the Crawlee issue created an issue here: https://github.com/apify/crawlee/issues/2282

**Comment by B4nan** [comment] 2024-01-12 14:12
> For the Crawlee issue

The same problem is present here as well, or better say, in the project docs, e.g. in SDK or client, where we also have API reference.

So I guess let's keep this one open so we don't forget to fix it here too.

**Comment by webrdaniel** [comment] 2024-01-12 14:35
> > For the Crawlee issue
> 
> The same problem is present here as well, or better say, in the project docs, e.g. in SDK or client, where we also have API reference. Hopefully this can be fixed from inside the shared docusaurus theme which is defined in this repository.
> 
> So I guess let's keep this one open so we don't forget to fix it here too. (and changing the labels as this part is on our shoulders)

@B4nan Ok, thanks 👍

**Closed** 2024-02-02 14:45 UTC
Labels: bug, low priority, t-tooling
