### ISSUE TITLE
Add mentions and usage examples of the Python Client

### ISSUE THREAD

**Issue by fnesveda** [apify/apify-docs#251] opened 2021-06-09 17:14 UTC
Throughout the docs, we're mentioning the Apify API Client for Javascript, and we have some usage examples on how to access various storages etc., we should do the same for the Python Client to make it easier for users to utilize it.

**Comment by fnesveda** [comment] 2022-05-18 12:25
Let's do it together with adding snippets for the Python SDK, once we have it.

**Comment by mtrunkat** [comment] 2023-07-24 13:37
Closing as duplicate of #652

**Closed** 2023-07-24 13:38 UTC
Labels: documentation, enhancement
