### ISSUE TITLE
Check potentially missing pages

### ISSUE THREAD

**Issue by HonzaKirchner** [apify/apify-docs#610] opened 2023-06-09 15:08 UTC
Some of. the content might have been deleted while merging docs sites. Here is a list of sites thatwere possibly affected.
We should check and add them again in case they are gone. Original commit is [here](https://github.com/apify/apify-docs/commit/49553ada4a2693a97fee115b51c06a8b187aa96b)

```
D       content/academy/anti_scraping/mitigation.md
D       content/docs/actors.md
D       content/docs/proxy/residential_proxy/tips_and_tricks.md
D       content/docs/storage/key_value_store.md
D       content/docs/tutorials.md
D       content/docs/tutorials/analyze_pages_and_fix_errors.md
D       content/docs/tutorials/apify_scrapers/cheerio_scraper.md
D       content/docs/tutorials/apify_scrapers/getting_started.md
D       content/docs/tutorials/apify_scrapers/puppeteer_scraper.md
D       content/docs/tutorials/apify_scrapers/web_scraper.md
D       content/docs/tutorials/cache_data_to_improve_performance.md
D       content/docs/tutorials/crawl_urls_from_a_google_sheet.md
D       content/docs/tutorials/log_in_by_transferring_cookies.md
D       content/docs/tutorials/log_into_a_website_using_puppeteer.md
D       content/docs/tutorials/scrape_data_using_python.md
D       content/docs/tutorials/scrape_paginated_sites.md
D       content/docs/tutorials/scrape_websites_using_the_sitemap.md
D       content/docs/tutorials/scraping_dynamic_content.md
D       content/docs/tutorials/use_apify_from_php.md
D       content/docs/web_scraping_101.md
D       content/docs/web_scraping_101/anti_scraping_techniques.md
D       content/docs/web_scraping_101/web_scraping_techniques.md
```
Reported [here](https://apifier.slack.com/archives/C0L33UM7Z/p1686309451542209)

**Comment by mtrunkat** [comment] 2023-06-13 08:28
@HonzaKirchner @valekjo  Isn't this a duplicate of https://github.com/apify/apify-docs/issues/612

**Comment by valekjo** [comment] 2023-06-13 09:27
Oh, yeah, it is, closing the newer one.

**Comment by B4nan** [comment] 2023-07-27 14:11
Went through the list and it looks good to me (except one missing redirect):

- `content/academy/anti_scraping/mitigation.md` -> https://docs.apify.com/academy/anti-scraping/mitigation
- `content/docs/actors.md` -> https://docs.apify.com/platform/actors
- `content/docs/proxy/residential_proxy/tips_and_tricks.md` -> removed by #575, so expected but we were missing a redirect (added)
- `content/docs/storage/key_value_store.md` -> https://docs.apify.com/platform/storage/key-value-store
- `content/docs/tutorials.md` -> https://docs.apify.com/academy/tutorials (we have redirects for all the tutorials)
- `content/docs/tutorials/use_apify_from_php.md` -> https://docs.apify.com/academy/php/use-apify-from-php (we have redirects)
- `content/docs/web_scraping_101.md` -> https://docs.apify.com/academy/web-scraping-for-beginners (we have redirects)
- `content/docs/web_scraping_101/anti_scraping_techniques.md` -> https://docs.apify.com/academy/anti-scraping/techniques (we have redirects)
- `content/docs/web_scraping_101/web_scraping_techniques.md` -> https://docs.apify.com/academy/concepts (we have redirects)

**Closed by B4nan** 2023-07-27 14:11 UTC
Labels: bug, documentation, t-tooling
