### ISSUE TITLE
Delete single-file actor docs

### ISSUE THREAD

**Issue by m-murasovs** [apify/apify-docs#366] opened 2022-05-17 09:07 UTC
https://apifier.slack.com/archives/C0L33UM7Z/p1652778044159359

**Comment by mtrunkat** [comment] 2022-05-17 19:31
Or remove? https://blog.apify.com/single-javascript-file-actors-are-being-deprecated/

**Comment by fnesveda** [comment] 2022-05-18 12:41
Closing, duplicate of https://github.com/apify/apify-core/issues/4859

**Closed by fnesveda** 2022-05-18 12:41 UTC
Labels: bug, debt
